workspace:
  base: /go
  path: src/github.com/cjsaylor/boxmeup-go

pipeline:
  setup:
    image: mysql:5.6
    commands:
      - sleep 15
      - cat schema.sql | mysql -u root -psupersecret -h mysql bmu_test
  test:
    image: golang:1.9.2-alpine
    environment:
      - MYSQL_DSN=root:supersecret@tcp(mysql:3306)/bmu_test
    commands:
      - go get -u golang.org/x/tools/cmd/cover
      - go generate -v -x ./...
      - go test -cover $(go list ./... | grep -v /vendor/)
  publish:
    image: plugins/docker
    repo: cjsaylor/boxmeup-go
    secrets: [ docker_username, docker_password ]
    tag: [ latest ]
    when:
      branch: master
      event: push

services:
  mysql:
    image: mysql:5.6
    environment:
      - MYSQL_DATABASE=bmu_test
      - MYSQL_ROOT_PASSWORD=supersecret